version: '3.9'

services:
  sonarqube:
    platform: linux/amd64
    image: sonarqube
    container_name: sonarqube
    # environment:
    #   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqubedb:5432/sonar
    #   - SONARQUBE_JDBC_USERNAME=sonar
    #   - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonarqube-net
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  # sonarqubedb:
  #   image: postgres
  #   container_name: sonarqubedb
  #   networks:
  #     - sonarqube-net
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   volumes:
  #     - sonarqube_postgresql:/var/lib/postgresql
  #     - sonarqube_postgresql_data:/var/lib/postgresql/data

networks:  
  sonarqube-net:

volumes:  
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_bundled-plugins:
  # sonarqube_postgresql:
  # sonarqube_postgresql_data:
